### ISSUE TITLE
*-print-default-mapping prints nothing?

### ISSUE THREAD

**Issue by daslicht** [jhorology/nks-presets-collection#5]
see:

```
daslicht:nks-presets-collection-master daslicht$ gulp serum-print-default-mapping
[12:44:42] Using gulpfile ~/Downloads/nks-presets-collection-master/gulpfile.js
[12:44:42] Starting 'serum-print-default-mapping'...
[12:44:42] Finished 'serum-print-default-mapping' after 14 ms
```

**Comment by jhorology** [comment]
Please try node v5.x.x.  I just updated README.md.

**Comment by daslicht** [comment]
```
daslicht:~ daslicht$ node -v
v5.8.0
```

**Comment by daslicht** [comment]
already have node 5

**Comment by daslicht** [comment]
still not working even tho I switched to you suggested version of node:
idea?

```
daslicht:nks-presets-collection daslicht$ node -v
v5.11.1
daslicht:nks-presets-collection daslicht$ gulp serum-print-default-mapping
[17:37:44] Requiring external module coffee-script/register
[17:37:45] Using gulpfile ~/DEV/nks-presets-collection/gulpfile.coffee
[17:37:45] Starting 'serum-print-default-mapping'...
[17:37:45] Finished 'serum-print-default-mapping' after 12 ms
daslicht:nks-presets-collection daslicht$ 
```

**Comment by daslicht** [comment]
I found the error:
you use a user path like this : 
```
/Users/daslicht/Documents/Native Instruments/User Content/Serum/
```
But that is not a valid path in the terminal 
it needs to be :
```
/Users/daslicht/Documents/Native\ Instruments/User\ Content/Serum/
```
